from enum import StrEnum


class LifecycleStatus(StrEnum):
    ENGINEERING = "ENGINEERING"
    PHYSICAL_SAMPLE_TESTED = "PHYSICAL_SAMPLE_TESTED"
    FIT_VALIDATED = "FIT_VALIDATED"
    PRODUCTION_APPROVED = "PRODUCTION_APPROVED"


class ValidationStatus(StrEnum):
    UNVALIDATED_FOR_PRODUCTION = "UNVALIDATED_FOR_PRODUCTION"
    VALIDATED_FOR_PRODUCTION = "VALIDATED_FOR_PRODUCTION"


class MeasurementKind(StrEnum):
    BODY = "BODY"
    GARMENT = "GARMENT"
    PATTERN = "PATTERN"


class ProvenanceStatus(StrEnum):
    ASSUMPTION = "ASSUMPTION"
    DERIVED = "DERIVED"
    PUBLISHED_REFERENCE = "PUBLISHED_REFERENCE"
    OBSERVED = "OBSERVED"


class OrderStatus(StrEnum):
    PREPARED_FOR_OPTIMIZATION = "PREPARED_FOR_OPTIMIZATION"


class OptimizationCompletionStatus(StrEnum):
    FEASIBLE_NOT_PROVEN_BEST = "FEASIBLE_NOT_PROVEN_BEST"
    OPTIMAL = "OPTIMAL"

